from .hard1 import HARD1
from .normal1 import NORMAL1
from .normal2 import NORMAL2
from .normal3 import NORMAL3
from .normal4 import NORMAL4
from .tutorial1 import TUTORIAL1
from .tutorial2 import TUTORIAL2
from .tutorial3 import TUTORIAL3
from .tutorial4 import TUTORIAL4
from .tutorial5 import TUTORIAL5
from .practice1 import PRACTICE1
from .practice2 import PRACTICE2
from .practice3 import PRACTICE3
from .practice4 import PRACTICE4
from .practice5 import PRACTICE5
